<?php include __DIR__ . '/functions.php'; ?>
<?php include $phireHeader; ?>
    <h1 class="navigation-header"><?=$title; ?> : <span id="title-span"><?=$navigation_title; ?></span></h1>
    <nav id="sub-nav">
<?php if ($acl->isAllowed($user->role, 'navigation', 'add')): ?>
        <nav><a href="<?=$phireUri; ?>/navigation/add">+ Add</a></nav>
<?php endif; ?>
        <nav><a href="<?=$phireUri; ?>/navigation">Back</a></nav>
    </nav>
    <form id="navigation-manage-form" action="<?=$phireUri . '/navigation/manage/' . $id; ?>" method="post">
        <div id="nav-manage-header">
<?php if ($acl->isAllowed($user->role, 'navigation', 'remove')): ?>
            <input type="submit" name="submit" class="save-btn" value="Save" tabindex="3000" />
<?php endif; ?>
            <div>
                <label for="nav_title">Add New Item</label>
                <input type="text" name="nav_title" id="nav_title" value="" size="60" placeholder="Title" tabindex="1" />
                <input type="text" name="nav_href" id="nav_href" value="" size="50" placeholder="Link" tabindex="2" />
                <input type="hidden" name="nav_id" id="nav_id" value="" tabindex="3" />
                <input type="hidden" name="nav_type" id="nav_type" value="" tabindex="4" />
            </div>
            <div>
                <select name="nav_from" id="nav_from" onchange="phire.changeNavItem();" tabindex="5">
                    <option value="----">[ Add Item ]</option>
<?php foreach ($selectFrom['content'] as $type => $content): ?>
                    <optgroup label="<?=$type; ?>">
<?php foreach ($content as $c): ?>
                        <option value="<?=$c['id'];?>|content|<?=BASE_PATH . $c['uri']; ?>|<?=$c['title']; ?>"><?=str_repeat('&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;', $c['depth']) . (($c['depth'] > 0) ? '&rarr; ' : '') . $c['title']; ?></option>
<?php endforeach; ?>
                    </optgroup>
<?php endforeach; ?>
<?php if (count($selectFrom['categories']) > 0): ?>
                    <optgroup label="Categories">
<?php foreach ($selectFrom['categories'] as $c): ?>
                        <option value="<?=$c['id'];?>|category|<?=BASE_PATH . '/category' . $c['uri']; ?>|<?=$c['title']; ?>"><?=str_repeat('&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;', $c['depth']) . (($c['depth'] > 0) ? '&rarr; ' : '') . $c['title']; ?></option>
<?php endforeach; ?>
                    </optgroup>
<?php endif; ?>
                </select>
                <select name="nav_action_object" tabindex="7">
                    <option value="----">[ To ]</option>
<?php if (count($tree) > 0): ?>
<?php printNavOptions($tree); ?>
<?php endif; ?>
                </select>
                <select name="nav_target" tabindex="8">
                    <option value="----">[ Target ]</option>
                    <option value="_blank">New</option>
                    <option value="_parent">Parent</option>
                    <option value="_top">Top</option>
                    <option value="false">False</option>
                </select>
            </div>
        </div>
        <div id="nav-tree">
<?php if (count($tree) > 0): ?>
<?php printNavTree($tree); ?>
<?php else: ?>
            <p>There is currently nothing assigned to this navigation object.</p>
<?php endif; ?>
        </div>
<?php if ($acl->isAllowed($user->role, 'navigation', 'remove')): ?>
        <div id="nav-manage-footer">
            <input type="submit" name="submit" class="save-btn" value="Save" />
            <input type="hidden" name="id" id="id" value="<?=$id; ?>" />
        </div>
    </form>
<?php endif; ?>
<div id="nav-edit">
    <a href="#" class="nav-close-link" onclick="jax('#nav-edit').fade(0, {tween : 25, speed : 250}); return false;">close [x]</a>
    <form id="navigation-manage-edit-form" action="<?=$phireUri . '/navigation/manage/' . $id; ?>" method="post">
        <div>
            <input type="text" name="nav_edit_title" id="nav_edit_title" value="" size="55" placeholder="Title" />
        </div>
        <div>
            <input type="text" name="nav_edit_href" id="nav_edit_href" value="" size="55" placeholder="Link" />
            <select name="nav_edit_target" id="nav_edit_target">
                <option value="----">[ Target ]</option>
                <option value="_blank">New</option>
                <option value="_parent">Parent</option>
                <option value="_top">Top</option>
                <option value="false">False</option>
            </select>
        </div>
        <div>
            <input type="hidden" name="branch_to_edit" id="branch_to_edit" value="" />
            <input type="hidden" name="action_edit" id="action_edit" value="1" />
            <input type="hidden" name="id" id="id" value="<?=$id; ?>" />
            <input type="submit" name="submit" class="save-btn" value="Save" tabindex="3001" />
        </div>
    </form>
</div>
<?php include $phireFooter; ?>
